---
- name: Installing and Creating LAMP stack docker container
  hosts: all
  gather_facts: no
  tasks:
  - name: Update Repository Index
    apt: 
      update_cache: yes


  roles:
  - container
  - LAMP
