---
- name: Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: Install apache and php image
  docker_image: 
    name: romeoz/docker-apache-php
    state: present
    source: pull

- name: Install mysql-server image
  docker_image:
    name: mysql/mysql-server:latest
    state: present
    source: pull
# tasks file for LAMP
